# Generated by Django 5.2.8 on 2025-11-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_id_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('claim_type', models.CharField(choices=[('dismissal', 'פיטורים שלא כדין'), ('salary', 'אי תשלום שכר / הלנת שכר'), ('overtime', 'שעות נוספות'), ('rights', 'פגיעה בזכויות סוציאליות')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('had_hearing', models.BooleanField(default=False)),
                ('has_contract', models.BooleanField(default=False)),
                ('notes_from_chatbot', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'חדש'), ('in_review', 'בבדיקה'), ('closed', 'נסגר')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_datetime', models.DateTimeField()),
                ('approved_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('suggested', 'הוצע מועד חדש')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_documents/')),
                ('document_type', models.CharField(choices=[('contract', 'חוזה עבודה'), ('pay_slip', 'תלוש שכר'), ('termination_letter', 'מכתב פיטורים/התפטרות'), ('other', 'אחר')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
        ),
    ]
