# Generated by Django 5.2.8 on 2025-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('suggested', 'הוצע מועד חדש')], default='pending', max_length=20),
        ),
    ]
