# Generated by Django 5.2.1 on 2025-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(help_text='כתובת אתר של מאגר הידע')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal domain',
                'verbose_name_plural': 'Legal domains',
            },
        ),
    ]
