# Generated by Django 5.2.1 on 2025-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_botmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldomain',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='legaldomain',
            name='source_url',
            field=models.URLField(help_text='כתובת אתר של מאגר הידע', max_length=600),
        ),
    ]
