# Generated by Django 5.0.3 on 2025-12-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_legaldomain_name_alter_legaldomain_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='legal_domain',
            field=models.ForeignKey(blank=True, help_text='התחום המשפטי שנבחר בטופס - משמש לטעינת הודעות בוט', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.legaldomain'),
        ),
        migrations.AlterField(
            model_name='case',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('dismissal', 'פיטורים שלא כדין'), ('salary', 'אי תשלום שכר / הלנת שכר'), ('overtime', 'שעות נוספות'), ('rights', 'פגיעה בזכויות סוציאליות')], max_length=20, null=True),
        ),
    ]
