# Generated by Django 5.0.3 on 2025-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_legal_domain_alter_case_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldomain',
            name='source_url',
            field=models.URLField(help_text='כתובת אתר של מאגר הידע', max_length=1000),
        ),
    ]
