# Generated by Django 5.0.3 on 2025-12-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_legaldomain_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID ייחודי של ההודעה מ-WhatsApp', max_length=255, unique=True)),
                ('from_number', models.CharField(help_text='מספר השולח', max_length=30)),
                ('to_number', models.CharField(help_text='מספר הנמען', max_length=30)),
                ('message_text', models.TextField(help_text='תוכן ההודעה')),
                ('is_from_lawyer', models.BooleanField(default=False, help_text='האם ההודעה נשלחה מעורך הדין')),
                ('timestamp', models.DateTimeField(help_text='זמן שליחת ההודעה')),
                ('message_type', models.CharField(default='text', help_text='סוג ההודעה (text, image, document, etc.)', max_length=20)),
                ('has_media', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True, help_text='קישור למדיה אם יש', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='התיק הקשור לשיחה', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='cases.case')),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['case', '-timestamp'], name='cases_whats_case_id_97512c_idx'), models.Index(fields=['from_number', '-timestamp'], name='cases_whats_from_nu_ea172a_idx')],
            },
        ),
    ]
